# Generated by Django 4.0.4 on 2022-09-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyximApp', '0003_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
