# Generated by Django 4.0.4 on 2022-10-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyximApp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_replies', to='PyximApp.comment'),
        ),
    ]
