# Generated by Django 4.0.4 on 2022-10-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyximApp', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to='PyximApp.record'),
        ),
    ]
